/**
 * Interactive Spectral Exploration
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The MetaFilter model module.
* @module model/MetaFilter
* @version 1.0.0
*/
export default class MetaFilter {
    /**
    * Constructs a new <code>MetaFilter</code>.
    * @alias module:model/MetaFilter
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>MetaFilter</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MetaFilter} obj Optional instance to populate.
    * @return {module:model/MetaFilter} The populated <code>MetaFilter</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetaFilter();
                        
            
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {String} key
    */
    'key' = undefined;
    /**
    * @member {Array.<String>} values
    */
    'values' = undefined;




}
