/**
 * Interactive Spectral Exploration
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Stat from './Stat';

/**
* The StatFilter model module.
* @module model/StatFilter
* @version 1.0.0
*/
export default class StatFilter {
    /**
    * Constructs a new <code>StatFilter</code>.
    * @alias module:model/StatFilter
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>StatFilter</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/StatFilter} obj Optional instance to populate.
    * @return {module:model/StatFilter} The populated <code>StatFilter</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatFilter();
                        
            
            if (data.hasOwnProperty('stat')) {
                obj['stat'] = Stat.constructFromObject(data['stat']);
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'Number');
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = ApiClient.convertToType(data['end'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Stat} stat
    */
    'stat' = undefined;
    /**
    * @member {Number} start
    */
    'start' = undefined;
    /**
    * @member {Number} end
    */
    'end' = undefined;




}
